import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv

load_dotenv()

def send_digest_email(articles):
    if not articles:
        print("No new articles to email.")
        return

    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    receiver = os.getenv("EMAIL_RECEIVER")

    # Build the email body
    body = "<h2>🤖 Your Daily AI News Digest</h2>"

    for article in articles:
        body += f"""
        <hr>
        <h3><a href="{article.url}">{article.title}</a></h3>
        <p><b>Source:</b> {article.source} | <b>Published:</b> {article.published_at}</p>
        <p>{article.summary or 'No summary yet.'}</p>
        """

    body += "<hr><p><i>Generated by your AI News Aggregator</i></p>"

    # Set up the email
    msg = MIMEMultipart("alternative")
    msg["Subject"] = "🤖 Daily AI News Digest"
    msg["From"] = sender
    msg["To"] = receiver
    msg.attach(MIMEText(body, "html"))

    # Send it
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, receiver, msg.as_string())

    print(f"Email sent to {receiver} with {len(articles)} articles!")