import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv
from app.models import Subscriber
from app.services.database import get_db

load_dotenv()

def send_digest_email(articles):
    if not articles:
        print("No new articles to email.")
        return

    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")

    # Get ALL active subscribers from database
    db = next(get_db())
    subscribers = db.query(Subscriber).filter_by(is_active=True).all()

    if not subscribers:
        print("No subscribers yet!")
        return

    # Build the email body
    body = "<h2>🤖 Your Daily AI News Digest</h2>"

    for article in articles:
        body += f"""
        <hr>
        <h3><a href="{article.url}">{article.title}</a></h3>
        <p><b>Source:</b> {article.source} | <b>Published:</b> {article.published_at}</p>
        <p>{article.summary or 'No summary yet.'}</p>
        """

    body += "<hr><p><i>Generated by AI News Aggregator</i></p>"

    # Send to each subscriber
    sent = 0
    for subscriber in subscribers:
        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = "🤖 Daily AI News Digest"
            msg["From"] = sender
            msg["To"] = subscriber.email
            msg.attach(MIMEText(body, "html"))

            with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
                server.login(sender, password)
                server.sendmail(sender, subscriber.email, msg.as_string())

            sent += 1
            print(f"Email sent to {subscriber.email}")
        except Exception as e:
            print(f"Failed to send to {subscriber.email}: {e}")

    print(f"\nDigest sent to {sent}/{len(subscribers)} subscribers!")